version: '3.8'

services:
  spinscribe:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/spinscribe
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
    depends_on:
      - db
      - redis
      - qdrant
    volumes:
      - ./storage:/app/storage

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spinscribe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:

