# File: docker-compose.yml
version: '3.12'

services:
  spinscribe:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MODEL_TYPE=gpt-4o
      - LOG_LEVEL=INFO
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - spinscribe-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - spinscribe-network

volumes:
  qdrant_storage:

networks:
  spinscribe-network:
    driver: bridge